version: '3.8'

services:
    laravel:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        container_name: ${APP_SERVICE}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://0.0.0.0:${APP_PORT}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        ports:
            - "${APP_PORT}:8080"
        volumes:
            - .:/var/www/html
        environment:
            WWWUSER: '${WWWUSER}'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD} # Ensure this matches the .env
        depends_on:
            - mysql_db   # Updated to match the MySQL service name
        networks:
            - laravel-network

    mysql_db:    # Ensure the service name matches here
        image: mysql:8.0
        container_name: ${DB_CONTAINER_NAME}
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}   # Should not be 'root'
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel-network

volumes:
    mysql_data:
        driver: local

networks:
    laravel-network:
        driver: bridge
